"""Fills in the missing amount=0.0 baseline row for the salt & pepper sweep.

salt_pepper_sweep_output/summary.csv was generated by an older run of
salt_pepper_sweep.py that didn't include amount=0.0 in SALT_PEPPER_AMOUNTS yet.
The other 9 levels (0.0001..0.01) are already computed and complete -- rather than
re-running the whole 7373-image x 10-level sweep from scratch, this script computes
just the missing level and merges it into the existing outputs.

Same protocol as salt_pepper_sweep.py's amount=0.0 case: clean_pred is one
dropout-active forward pass per image, and since perturb_salt_pepper(amount=0.0) is
a no-op, the "noisy" prediction is a SECOND independent dropout-active forward pass
on the same input -- so this measures the generator's own stochasticity floor, not a
trivial self-comparison (matches the Control level convention used for the other
three sweeps).

Run with: pixi run python salt_pepper_sweep_baseline.py
"""
import csv
import pathlib

import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_io as tfio
import torch
import lpips
from PIL import Image

from pix2pix import Generator, INPUT_CHANNELS

dataset_name = 'polyps_v7'
PATH = pathlib.Path(r'./datasets') / dataset_name
SPLIT = 'val'
AMOUNT = 0.0

out_root = pathlib.Path('./salt_pepper_sweep_output')
amt_dir = out_root / 'amt_0_0000'
amt_dir.mkdir(parents=True, exist_ok=True)

generator = Generator()
_ckpt = tf.train.Checkpoint(generator=generator)
_ckpt.restore(tf.train.latest_checkpoint('./training_checkpoints')).expect_partial()
print('Checkpoint restored')

loss_fn = lpips.LPIPS(net='alex', verbose=False)
image_fns = sorted((PATH / SPLIT).glob('*.tif'))
print(f'{len(image_fns)} val images found')


def to_lpips_tensor(img_m11):
    t = tf.cast(tf.transpose(img_m11[tf.newaxis], [0, 3, 1, 2]), tf.float32)
    return torch.utils.dlpack.from_dlpack(tf.experimental.dlpack.to_dlpack(t))


rows = []
for i, fn in enumerate(image_fns):
    raw = tf.io.read_file(str(fn))
    image = tfio.experimental.image.decode_tiff(raw)
    half = tf.shape(image)[1] // 2

    inp = tf.cast(image[:, half:, :INPUT_CHANNELS], tf.float32)
    inp = (inp / 127.5) - 1.0

    clean_pred = generator(inp[tf.newaxis], training=True)[0]
    clean_01 = clean_pred * 0.5 + 0.5
    clean_t = to_lpips_tensor(clean_pred)

    noisy_pred = generator(inp[tf.newaxis], training=True)[0]

    pred_np = ((noisy_pred.numpy() * 0.5 + 0.5) * 255).clip(0, 255).astype(np.uint8)
    Image.fromarray(pred_np).save(amt_dir / fn.name)

    pred_01 = noisy_pred * 0.5 + 0.5
    pred_t = to_lpips_tensor(noisy_pred)

    ssim_val = float(tf.image.ssim(pred_01, clean_01, max_val=1))
    psnr_val = float(tf.image.psnr(pred_01, clean_01, max_val=1))
    with torch.no_grad():
        lpips_val = float(loss_fn(pred_t, clean_t))

    rows.append({
        'file': fn.name,
        'ssim': round(ssim_val, 6),
        'psnr': round(psnr_val, 4),
        'lpips': round(lpips_val, 6),
    })

    if (i + 1) % 200 == 0 or (i + 1) == len(image_fns):
        print(f'  {i + 1}/{len(image_fns)} images')

per_csv = amt_dir / 'metrics.csv'
with open(per_csv, 'w', newline='') as fh:
    wr = csv.DictWriter(fh, fieldnames=['file', 'ssim', 'psnr', 'lpips'])
    wr.writeheader()
    wr.writerows(rows)

ssim_list = [r['ssim'] for r in rows]
psnr_list = [r['psnr'] for r in rows]
lpips_list = [r['lpips'] for r in rows]

new_row = {
    'amount': AMOUNT,
    'ssim_mean': round(float(np.mean(ssim_list)), 5),
    'ssim_std': round(float(np.std(ssim_list)), 5),
    'psnr_mean': round(float(np.mean(psnr_list)), 4),
    'psnr_std': round(float(np.std(psnr_list)), 4),
    'lpips_mean': round(float(np.mean(lpips_list)), 5),
    'lpips_std': round(float(np.std(lpips_list)), 5),
    'n_images': len(rows),
}
print(f"amount={AMOUNT:.4f}  SSIM {new_row['ssim_mean']:.4f}  "
      f"PSNR {new_row['psnr_mean']:.2f} dB  LPIPS {new_row['lpips_mean']:.4f}  "
      f"(n={new_row['n_images']})")

summary_csv = out_root / 'summary.csv'
df = pd.read_csv(summary_csv)
df = df[df['amount'] != AMOUNT]
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
df = df.sort_values('amount').reset_index(drop=True)
df.to_csv(summary_csv, index=False)
print(f'merged amount=0.0 into {summary_csv}')
print(df.to_string(index=False))
